<header id="site-header" class="site-header">
  <div class="site-container">
    <div class="top-menu">
      <a class="btn-nav" href="#"><span></span></a>
      <ul class="menu">
        <li><a href="#">Sushi Neko</a></li>
        <li><a href="#">Musashi’s</a></li>
        <li><a href="#">Will Rogers Theatre</a></li>
        <li class="img"><a href="#">Western Concept</a></li>
        <li><a href="#">The Lobby Cafe & Bar</a></li>
        <li><a href="#">The Coach House</a></li>
        <li><a href="#">The Tasting Room</a></li>
      </ul>
    </div>
    <div class="logo">
      <a href="13-0297-WC-Will-Rogers-Home.php"><img src="theme/images/logo.png" alt="logo"/>

        <h1>Will Rogers Theatre</h1></a>
    </div>
    <div class="social-share">
      <a class="colo" href="#colo"></a>
      <a class="facebook" href="#facebook"></a>
      <a class="twitter" href="#twitter"></a>
      <a class="zw" href="#zw"></a>
    </div>
    <nav class="nav">
      <a class="btn-nav" href="#">Navigation Menu</a>
      <ul class="menu">
        <li><a href="#">Weddings</a></li>
        <li><a href="13-0297-WC-Will-Rogers-Special-Events.php">special events</a></li>
        <li><a href="#">Gallery</a></li>
        <li><a href="13-0297-WC-Will-Rogers-Menu.php">Menu</a></li>
        <li><a href="#">about</a></li>
        <li><a href="13-0297-WC-Will-Rogers-Layout.php">Layout</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </nav>
  </div>
</header>
